[package]
name = "playground-tui"
version = "0.1.0"
description = "owl"
authors = ["Pierre Cochard <pierre.cochard@inria.fr>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
tui-big-text = "0.7.1"
tui-rain = "1.0.1"
